go test github.com/multiversx/mx-chain-go/factory/...
go test github.com/multiversx/mx-chain-go/genesis/...
go test github.com/multiversx/mx-chain-go/process/...
go test github.com/multiversx/mx-chain-go/vm/...
