[StakingSystemSCConfig]
    GenesisNodePrice = "20000" #20000 POWER
    MinStakeValue = "1" #1 POWER
    MinUnstakeTokensValue = "1" #1 POWER
    UnBondPeriod = 250
    UnBondPeriodInEpochs = 1
    MinStepValue = "1" #1 POWER
    NumRoundsWithoutBleed = 100
    MaximumPercentageToBleed = 0.5
    BleedPercentagePerRound = 0.00001
    MaxNumberOfNodesForStake = 64
    UnJailValue = "2500000000000000000" #25 OURO TODO: See to what should this value be set to
    ActivateBLSPubKeyMessageVerification = false
    StakeLimitPercentage = 1.0 #fraction of value 1 - 100%, for the time being no stake limit
    NodeLimitPercentage = 0.1 #fraction of value 0.1 - 10%

[ESDTSystemSCConfig]
    BaseIssuingCost = "5000000000000000000" #5 OURO
    OwnerAddress = "erd1fpkcgel4gcmh8zqqdt043yfcn5tyx8373kg6q2qmkxzu4dqamc0swts65c"

[GovernanceSystemSCConfig]
    OwnerAddress = "erd1vxy22x0fj4zv6hktmydg8vpfh6euv02cz4yg0aaws6rrad5a5awqgqky80" #should use a multisign contract instead of a wallet address
    [GovernanceSystemSCConfig.V1]
        NumNodes           = 500
        ProposalCost       = "5000000000000000000" #5 OURO
        MinQuorum          = 400
        MinPassThreshold   = 300
        MinVetoThreshold   = 50
    [GovernanceSystemSCConfig.Active]
        ProposalCost       = "1000000000000000000000" #1000 OURO
        LostProposalFee    = "10000000000000000000"   #10 OURO
        MinQuorum          = 0.2  #fraction of value 0.2  - 20%
        MinPassThreshold   = 0.5  #fraction of value 0.5  - 50%
        MinVetoThreshold   = 0.33 #fraction of value 0.33 - 33%

[DelegationManagerSystemSCConfig]
    MinCreationDeposit = "0" #0 POWER, irellevant since contracts override this
    MinStakeAmount = "1" #1 POWER
    ConfigChangeAddress = "erd1vxy22x0fj4zv6hktmydg8vpfh6euv02cz4yg0aaws6rrad5a5awqgqky80" #should use a multisign contract instead of a wallet address

[DelegationSystemSCConfig]
    MinServiceFee  = 0
    MaxServiceFee  = 10000

# Changing this config is not backwards compatible
[SoftAuctionConfig]
    TopUpStep = "1" # 1 POWER
    MinTopUp = "1" # 1 POWER
    MaxTopUp = "320000000" # 320,000,000 POWER
    MaxNumberOfIterations = 100000 # 100k max number of iterations for soft auction config
