#Economics config of the node
[GlobalSettings]
    GenesisTotalSupply = "2000000000000000000000" #2000 OURO
    MinimumInflation   = 0.0
    YearSettings = [
        {Year = 1, MaximumInflation  = 0.10845130},
        {Year = 2, MaximumInflation  = 0.09703538},
        {Year = 3, MaximumInflation  = 0.08561945},
        {Year = 4, MaximumInflation  = 0.07420352},
        {Year = 5, MaximumInflation  = 0.06278760},
        {Year = 6, MaximumInflation  = 0.05137167},
        {Year = 7, MaximumInflation  = 0.03995574},
        {Year = 8, MaximumInflation  = 0.02853982},
        {Year = 9, MaximumInflation  = 0.01712389},
        {Year = 10, MaximumInflation = 0.00570796},
        {Year = 11, MaximumInflation = 0.0},
    ]
    Denomination = 18 # represents the smallest OURO subdivision (10^-X OURO for a denomination of X)
    GenesisMintingSenderAddress = "erd17rc0pu8s7rc0pu8s7rc0pu8s7rc0pu8s7rc0pu8s7rc0pu8s7rcqqkhty3"

[RewardsSettings]
    [[RewardsSettings.RewardsConfigByEpoch]]
    EpochEnable = 0
    LeaderPercentage = 0.1 #fraction of value 0.1 - 10%
    DeveloperPercentage = 0.3 #fraction of value 0.3 - 30%
    ProtocolSustainabilityPercentage = 0.31 #fraction of value 0.31 - 31% (21% - OURO Pie Distribution; 10% Coding Division; TODO: Only gas fees should go there)
    ProtocolSustainabilityAddress = "erd1gzsug2n6th3qztpvgnzqx640azvqkv5phmktrdq766tzxx0zt4jszw8672"
    TopUpGradientPoint = "20000000" # 20,000,000 POWER (eligible topUp)
    TopUpFactor = 0.5 # fraction of value 0.5 - 50%

[FeeSettings]
    GasLimitSettings = [
        {EnableEpoch = 0, MaxGasLimitPerBlock = "1500000000", MaxGasLimitPerMiniBlock = "250000000", MaxGasLimitPerMetaBlock = "15000000000", MaxGasLimitPerMetaMiniBlock = "250000000", MaxGasLimitPerTx = "600000000", MinGasLimit = "50000", ExtraGasLimitGuardedTx  = "50000"},
    ]
    MinGasPrice             = "1000000000" #will yield min tx fee of 0.00005 OURO
    GasPriceModifier        = 0.01
    GasPerDataByte          = "1500"
    DataLimitForBaseCalc    = "10000"
    MaxGasPriceSetGuardian  = "2000000000"
